function cIdentifier(name) {
  const identifier = name.replace(/[^A-Za-z0-9_]/g, '_');
  return /^[A-Za-z_]/.test(identifier) ? identifier : `_${identifier}`;
}

function cType(type) {
  if (!type) return 'frontier_json_value';
  if (typeof type !== 'string') {
    if (type.kind === 'set' || type.kind === 'list' || type.kind === 'map') return 'frontier_json_value';
    if (type.kind === 'ref') return cIdentifier(type.name);
    return 'frontier_json_value';
  }
  const primitive = { Text: 'const char *', String: 'const char *', Bool: 'bool', Boolean: 'bool', Int: 'int64_t', Float: 'double', Number: 'double', Instant: 'const char *', Json: 'frontier_json_value', Patch: 'frontier_patch_list' };
  return primitive[type] ?? cIdentifier(type);
}

export function emitCHeader(document, options = {}) {
  const guard = cIdentifier((options.guard ?? `${document.name}_FRONTIER_LANG_H`).toUpperCase());
  const lines = [];
  const banner = options.banner ?? 'Generated by @shapeshift-labs/frontier-lang-c.';
  lines.push(`/* ${banner} */`, `#ifndef ${guard}`, `#define ${guard}`, '', '#include <stdbool.h>', '#include <stdint.h>', '', 'typedef struct frontier_json_value frontier_json_value;', 'typedef struct frontier_patch_list frontier_patch_list;', '');
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'type' && node.fields?.length) emitStruct(lines, node.name, node.fields);
    if (node.kind === 'entity') emitStruct(lines, node.name, node.fields);
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'action') lines.push(`frontier_patch_list ${cIdentifier(node.name)}(const frontier_json_value *state, ${cType(node.input)} input);`, '');
  }
  lines.push(`#endif /* ${guard} */`);
  return `${lines.join('\n').trimEnd()}\n`;
}

function emitStruct(lines, name, fields) {
  lines.push(`typedef struct ${cIdentifier(name)} {`);
  for (const field of fields) lines.push(`  ${cType(field.type)} ${cIdentifier(field.name)};`);
  lines.push(`} ${cIdentifier(name)};`, '');
}
