function cIdentifier(name) {
  const identifier = name.replace(/[^A-Za-z0-9_]/g, '_');
  return /^[A-Za-z_]/.test(identifier) ? identifier : `_${identifier}`;
}

function cConstIdentifier(name) {
  return cIdentifier(name).replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
}

function cType(type) {
  if (!type) return 'frontier_json_value';
  if (typeof type !== 'string') {
    if (type.kind === 'set' || type.kind === 'list' || type.kind === 'map') return 'frontier_json_value';
    if (type.kind === 'ref') return cIdentifier(type.name);
    return 'frontier_json_value';
  }
  const primitive = { Text: 'const char *', String: 'const char *', Bool: 'bool', Boolean: 'bool', Int: 'int64_t', Float: 'double', Number: 'double', Instant: 'const char *', Json: 'frontier_json_value', Patch: 'frontier_patch_list' };
  return primitive[type] ?? cIdentifier(type);
}

function sourceRef(node, extra = {}) {
  return {
    semanticNodeId: node.id,
    semanticNodeKind: node.kind,
    semanticNodeName: node.name,
    ...extra
  };
}

export function toCAst(document, options = {}) {
  const guard = cIdentifier((options.guard ?? `${document.name}_FRONTIER_LANG_H`).toUpperCase());
  const banner = options.banner ?? 'Generated by @shapeshift-labs/frontier-lang-c.';
  const declarations = [
    { kind: 'opaqueStruct', name: 'frontier_json_value' },
    { kind: 'opaqueStruct', name: 'frontier_patch_list' }
  ];
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'type' && node.fields?.length) declarations.push(structItem(node, node.fields));
    if (node.kind === 'entity') declarations.push(structItem(node, node.fields));
    if (node.kind === 'capability') declarations.push({
      kind: 'capabilityMacro',
      name: `${cConstIdentifier(node.name)}_CAPABILITY`,
      value: node.capability,
      sourceRef: sourceRef(node)
    });
  }
  for (const node of Object.values(document.nodes)) {
    if (node.kind === 'action') {
      declarations.push({
        kind: 'functionPrototype',
        name: cIdentifier(node.name),
        returnType: 'frontier_patch_list',
        parameters: [
          { name: 'state', type: 'const frontier_json_value *' },
          { name: 'input', type: cType(node.input) }
        ],
        sourceRef: sourceRef(node)
      });
    }
  }
  return { kind: 'c.header', banner, guard, declarations };
}

export function renderCAst(ast) {
  const lines = [];
  lines.push(`/* ${ast.banner} */`, `#ifndef ${ast.guard}`, `#define ${ast.guard}`, '', '#include <stdbool.h>', '#include <stdint.h>', '');
  for (const declaration of ast.declarations) {
    if (declaration.kind === 'opaqueStruct') lines.push(`typedef struct ${declaration.name} ${declaration.name};`);
    if (declaration.kind === 'capabilityMacro') lines.push(`#define ${declaration.name} ${JSON.stringify(declaration.value)}`);
  }
  lines.push('');
  for (const declaration of ast.declarations) {
    if (declaration.kind === 'struct') renderStruct(lines, declaration);
    if (declaration.kind === 'functionPrototype') {
      const parameters = declaration.parameters.map((parameter) => `${parameter.type} ${parameter.name}`).join(', ');
      lines.push(`${declaration.returnType} ${declaration.name}(${parameters});`, '');
    }
  }
  lines.push(`#endif /* ${ast.guard} */`);
  return `${lines.join('\n').trimEnd()}\n`;
}

export function emitCHeader(document, options = {}) {
  return renderCAst(toCAst(document, options));
}

function structItem(node, fields) {
  return {
    kind: 'struct',
    name: cIdentifier(node.name),
    fields: fields.map((field) => ({ name: cIdentifier(field.name), type: cType(field.type) })),
    sourceRef: sourceRef(node, { regionIds: fields.map((field) => field.id) })
  };
}

function renderStruct(lines, declaration) {
  lines.push(`typedef struct ${declaration.name} {`);
  for (const field of declaration.fields) lines.push(`  ${field.type} ${field.name};`);
  lines.push(`} ${declaration.name};`, '');
}
